// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: internal/infra/grpc/protofiles/get_order.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GetOrderService_GetOrderById_FullMethodName = "/pb.GetOrderService/GetOrderById"
	GetOrderService_GetAllOrders_FullMethodName = "/pb.GetOrderService/GetAllOrders"
)

// GetOrderServiceClient is the client API for GetOrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetOrderServiceClient interface {
	GetOrderById(ctx context.Context, in *GetOrderByIdRequest, opts ...grpc.CallOption) (*Order, error)
	GetAllOrders(ctx context.Context, in *Blank, opts ...grpc.CallOption) (*GetOrdersResponse, error)
}

type getOrderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGetOrderServiceClient(cc grpc.ClientConnInterface) GetOrderServiceClient {
	return &getOrderServiceClient{cc}
}

func (c *getOrderServiceClient) GetOrderById(ctx context.Context, in *GetOrderByIdRequest, opts ...grpc.CallOption) (*Order, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Order)
	err := c.cc.Invoke(ctx, GetOrderService_GetOrderById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *getOrderServiceClient) GetAllOrders(ctx context.Context, in *Blank, opts ...grpc.CallOption) (*GetOrdersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrdersResponse)
	err := c.cc.Invoke(ctx, GetOrderService_GetAllOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetOrderServiceServer is the server API for GetOrderService service.
// All implementations must embed UnimplementedGetOrderServiceServer
// for forward compatibility.
type GetOrderServiceServer interface {
	GetOrderById(context.Context, *GetOrderByIdRequest) (*Order, error)
	GetAllOrders(context.Context, *Blank) (*GetOrdersResponse, error)
	mustEmbedUnimplementedGetOrderServiceServer()
}

// UnimplementedGetOrderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGetOrderServiceServer struct{}

func (UnimplementedGetOrderServiceServer) GetOrderById(context.Context, *GetOrderByIdRequest) (*Order, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderById not implemented")
}
func (UnimplementedGetOrderServiceServer) GetAllOrders(context.Context, *Blank) (*GetOrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllOrders not implemented")
}
func (UnimplementedGetOrderServiceServer) mustEmbedUnimplementedGetOrderServiceServer() {}
func (UnimplementedGetOrderServiceServer) testEmbeddedByValue()                         {}

// UnsafeGetOrderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetOrderServiceServer will
// result in compilation errors.
type UnsafeGetOrderServiceServer interface {
	mustEmbedUnimplementedGetOrderServiceServer()
}

func RegisterGetOrderServiceServer(s grpc.ServiceRegistrar, srv GetOrderServiceServer) {
	// If the following call pancis, it indicates UnimplementedGetOrderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GetOrderService_ServiceDesc, srv)
}

func _GetOrderService_GetOrderById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetOrderServiceServer).GetOrderById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GetOrderService_GetOrderById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetOrderServiceServer).GetOrderById(ctx, req.(*GetOrderByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GetOrderService_GetAllOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Blank)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetOrderServiceServer).GetAllOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GetOrderService_GetAllOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetOrderServiceServer).GetAllOrders(ctx, req.(*Blank))
	}
	return interceptor(ctx, in, info, handler)
}

// GetOrderService_ServiceDesc is the grpc.ServiceDesc for GetOrderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetOrderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.GetOrderService",
	HandlerType: (*GetOrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrderById",
			Handler:    _GetOrderService_GetOrderById_Handler,
		},
		{
			MethodName: "GetAllOrders",
			Handler:    _GetOrderService_GetAllOrders_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/infra/grpc/protofiles/get_order.proto",
}
